### PR TITLE
Added github automated test workflow 

### PR DESCRIPTION
**Pull request by Liupold**
https://github.com/KristoforMaynard/music-tag/issues/15

Working. (All test passed). (And This resolves the issue).

### CODE REVIEW

**Comment by Liupold** [comment]
Added a basic github workflow to make testing easier.

**Comment by Liupold** [comment]
Reverted the requested change.

**Comment by Liupold** [comment]
This build the package using setup.py, (on 4 different version of python), And test using your script. (test/run_tests.sh).

**Comment by KristoforMaynard** [comment]
Slick, thanks! I generally find merges confusing (I'm more a fan of rebasing), but it looks like cb49039 will make a rebase fail. Instead I'll just cherry-pick the commits into master.

**Pull request closed without merging**
